# Macos
- block:
    - name: ensure not running all tasks with sudo
      fail:
        msg: "Do not run all tasks with sudo"
      when:
        - ansible_env.USER == "root"

    - name: dot files
      copy:
        src: "{{ item }}"
        dest: "{{ ansible_env.HOME }}/.{{ item }}"
        owner: "{{ ansible_env.USER }}"
        group: staff
        mode: 0600
      with_items:
        - bash_profile
        - terraformrc

    - name: dot files templates
      template:
        src: "{{ item }}"
        dest: "{{ ansible_env.HOME }}/.{{ item }}"
        owner: "{{ ansible_env.USER }}"
        group: staff
        mode: 0600
      with_items:
        - ansible.cfg

    - name: ssh config directory
      file:
        path: "{{ ansible_env.HOME }}/.ssh/conf.d"
        state: directory
        owner: "{{ ansible_env.USER }}"
        group: staff
        mode: 0700

    - name: ssh config
      copy:
        src: ssh_config 
        dest: "{{ ansible_env.HOME }}/.ssh/config"
        owner: "{{ ansible_env.USER }}"
        group: staff
        mode: 0600

    - name: packages - pip3
      become: yes
      pip:
        name: "{{ item }}"
        executable: pip3
        state: present
      with_items:
        - awscli
        - boto3

    - name: package - heptio-authenticator-aws
      get_url:
        url: "https://github.com/heptio/authenticator/releases/download/v{{ heptio_auth_aws_version }}/heptio-authenticator-aws_{{ heptio_auth_aws_version }}_darwin_amd64"
        dest: "/usr/local/bin/heptio-authenticator-aws"
        owner: "{{ ansible_env.USER }}"
        group: admin
        mode: 0755
        checksum: "sha256:{{ heptio_auth_aws_checksum }}"

    - name: homebrew - update homebrew and upgrade all packages
      homebrew:
        update_homebrew: yes
        upgrade_all: yes

  when:
    ansible_distribution == "MacOSX"
